name = "tmcp-fetch"
account_id = "44321e1b7fbd29b56b65c1890a3bbee2"
compatibility_date = "2025-09-14"
compatibility_flags = ["nodejs_compat"]

main = "src/index.ts"

workers_dev = true
preview_urls = false

[[durable_objects.bindings]]
name = "TMCP_DURABLE_OBJECT"
class_name = "SyncLayer"
