name = "tmcp-web"
account_id = "44321e1b7fbd29b56b65c1890a3bbee2"
compatibility_date = "2025-09-14"
compatibility_flags = ["nodejs_compat"]

main = "src/index.ts"

workers_dev = true
preview_urls = false

[observability]
enabled = true

[ai]
binding = "AI"
remote = true

[[durable_objects.bindings]]
name = "TMCP_DURABLE_OBJECT"
class_name = "SyncLayer"

[[kv_namespaces]]
binding = "TMCP_SESSION_INFO"
id = "3926d2c83ece42ddab17ae7f5e9c6aba"

[[migrations]]
tag = "v1"
new_classes = [ "SyncLayer" ]
